// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/driver/driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_driver_driver_proto protoreflect.FileDescriptor

const file_proto_driver_driver_proto_rawDesc = "" +
	"\n" +
	"\x19proto/driver/driver.proto\x12\x06driver\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19proto/driver/config.proto2:\n" +
	"\x06Driver\x120\n" +
	"\x06Config\x12\x16.google.protobuf.Empty\x1a\x0e.driver.ConfigB\n" +
	"Z\b./driverb\x06proto3"

var file_proto_driver_driver_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
	(*Config)(nil),        // 1: driver.Config
}
var file_proto_driver_driver_proto_depIdxs = []int32{
	0, // 0: driver.Driver.Config:input_type -> google.protobuf.Empty
	1, // 1: driver.Driver.Config:output_type -> driver.Config
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_driver_driver_proto_init() }
func file_proto_driver_driver_proto_init() {
	if File_proto_driver_driver_proto != nil {
		return
	}
	file_proto_driver_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_driver_driver_proto_rawDesc), len(file_proto_driver_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_driver_driver_proto_goTypes,
		DependencyIndexes: file_proto_driver_driver_proto_depIdxs,
	}.Build()
	File_proto_driver_driver_proto = out.File
	file_proto_driver_driver_proto_goTypes = nil
	file_proto_driver_driver_proto_depIdxs = nil
}
